### ISSUE TITLE
:w files - can't clone all branches

### ISSUE THREAD

**Issue by pgavigan** [HamnaNimra/SYSC4907-SAV#8]
The presence of :w files in some of the branches causes errors when cloning the repository.

Are these files used? Please remove or rename these files.

**Comment by JaskaranW** [comment]
No this was an error and there is no need of the ":w" files. This  is now fixed and will but pushed to repository in the next commit/push

**Comment by HamnaNimra** [comment]
The error still persists
![image](https://user-images.githubusercontent.com/38963550/111078685-1dea7980-84cd-11eb-90cc-358a2c955a76.png)

**Comment by JaskaranW** [comment]
Hmm Sorry about that must have missed it. what is the exact path to this folder?

**Comment by HamnaNimra** [comment]
Fixed by removing all the unwanted files
